name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Perbarui ke v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Perbarui ke v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        
      #   - name: Build project
      #     run: npm run build # Sesuaikan dengan perintah build proyek Anda

      - name: Ensure .ssh directory exists in runner
        run: |
          # Buat folder .ssh di direktori /home/runner (home directory)
          mkdir -p /home/runner/.ssh
          ls -la /home/runner/.ssh  # Pastikan folder .ssh ada di path ini

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Debug: Periksa isi folder .ssh di runner
          ls -la /home/runner/.ssh
          
          # Menyimpan SSH Key dan memastikan hak akses
          echo "$SSH_KEY" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          
          # Debug: Pastikan id_rsa telah dibuat
          ls -la /home/runner/.ssh
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.104.64.107 "cd 24001200-km7-mas-uploadfile-ch6/ && git pull origin main && npm install && pm2 stop all && npx prisma generate && pm2 start npm -- start"  # Sesuaikan path dan perintah start sesuai kebutuhan
